name=Tiny Electronic Blog Library
version=0.1
author=Tiny Electronic Blog <tinyelectronicblog@gmail.com>
maintainer=Tiny Electronic Blog <tinyelectronicblog@gmail.com>
sentence=The official library of Tiny Electronig Blog for Arduino.
paragraph=Currently supported development boards: ESP32.
category=Other
url=https://github.com/TinyElectronicBlog/TEB_Library
architectures=esp32
includes=TEB_Library.h